version: '2'

services:
  wordpress:
    container_name: wpproudcity_wordpress_1
    depends_on:
      - db
      # Uncomment for elasticsearch
      - elasticsearch
      - elasticdocapi
    # Uncomment for elasticsearch
    links:
      - 'elasticsearch:elasticsearchdocs.elasticsearch'
      - 'elasticdocapi:docsapi.elasticsearch'
    command: ['apache2-foreground']
    entrypoint: /app/bin/entrypoint.sh
    image: gcr.io/proudcity-1184/wp-proudcity:staging-771560f14403116e7c685eecd5229f1aa1c27c7e
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      #- wp-proudcity-sync:/app/wordpress:nocopy # nocopy is important
      - ./bin:/app/bin
      - ./wordpress:/app/wordpress
      # Exclude node_modules dirs for better performance
      - ./node_modules:/app/wordpress/wp-content/plugins/wp-proud-admin/node_modules
      - ./node_modules:/app/wordpress/wp-content/themes/wp-proud-theme/node_modules
      - ./node_modules:/app/wordpress/wp-content/themes/wp-proud-theme-intranet/node_modules
    tty: true
    ports:
      - '8000:80'
    # Uncomment for elasticsearch
    networks:
      - default
      - es-net
    environment:
      AUTH_REQUIRED:
      AUTH_USERNAME:
      AUTH_PASSWORD:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: db
      #WORDPRESS_DB_PORT: "**LinkMe**"
      HOST: localhost:8000
      APP: beta
      WORDPRESS_AUTH_KEY:
      WORDPRESS_SECURE_AUTH_KEY:
      WORDPRESS_LOGGED_IN_KEY:
      WORDPRESS_AUTH_SALT:
      WORDPRESS_SECURE_AUTH_SALT:
      WORDPRESS_LOGGED_IN_SALT:
      WORDPRESS_NONCE_SALT:
      GRAVITATE_ENCRYPTION_KEY:
      STATELESS_MEDIA_KEY_FILE_PATH:
      STATELESS_MEDIA_BUCKET:
      STATELESS_MEDIA_DIRECTORY:
      STATELESS_MEDIA_CACHE_BUSTING: '1' # defaults to false
      REDIS_SESSION: 'false' # no longer supported
      # @TODO set back to 256
      PHP_MEMORY_LIMIT: 2048M
      SMTP_HOST:
      SMTP_PASS:
      SMTP_USER:
      BLOCK_LOGIN:
      WP_REDIS_BACKEND_HOST:
      WP_REDIS_BACKEND_AUTH:
      # Uncomment for elasticsearch
      # ELASTICSEARCH_HOST:
      ELASTICSEARCH_HOST: 'elasticsearchdocs.elasticsearch'
      # Uncomment for elasticsearch
      # ELASTICSEARCH_DOCS_HOST:
      ELASTICSEARCH_DOCS_HOST: 'docsapi.elasticsearch'
      UPLOAD_MAX_FILESIZE: 25M
      # GOOGLE_GIT_TOKEN: # set this to download private repos and $WORDPRESS_PLUGINS in entrypoint.sh
      # WORDPRESSORG_PLUGINS:  # These plugins (csv of slugs) will be downloaded on container start (requires $GOOGLE_GIT_TOKEN)
      # WORDPRESS_PLUGINS:  # These plugins (git repo) will be downloaded on container start (requires $GOOGLE_GIT_TOKEN)
      # WORDPRESS_THEMES:  # These themes (git repo) will be downloaded on container start (requires $GOOGLE_GIT_TOKEN)
      # WORDPRESS_PLUGINS: "https://source.developers.google.com/p/proudcity-1184/r/wp-proud-sr-ca-widgets,https://github.com/SenecaSystems/romulus-wordpress-form.git,https://github.com/proudcity/wp-proud-directory.git"
      # WORDPRESSORG_PLUGINS: "buddypress,bp-default-data,buddypress-edit-activity,bbpress,buddydrive"
      # WORDPRESS_THEMES: "https://source.developers.google.com/p/proudcity-1184/r/wp-proud-sr-ca-theme"
      WP_CACHE: 0
      # @TODO set back to 0
      WP_DEBUG: 1
  db:
    image: mariadb
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
  # Uncomment for elasticsearch
  elasticsearch:
    platform: linux/amd64 # added
    container_name: elasticsearch
    # build: ./services/docker-elasticsearch-test
    # image: gcr.io/proudcity-1184/docker-elasticsearch-kubernetes:5.3.2
    # image: elastic/elasticsearch:5.3.2
    image: bitnami/elasticsearch:5.6.4-r0
    environment:
      - ELASTICSEARCH_PLUGINS=ingest-attachment
      - ELASTICSEARCH_SKIP_TRANSPORT_TLS=true
      - ELASTICSEARCH_LOCK_ALL_MEMORY=true
      - ELASTICSEARCH_IS_DEDICATED_NODE=true
      - ELASTICSEARCH_NODE_TYPE=master
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
      # - es.enforce.bootstrap.checks=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      # - data01:/bitnami/elasticsearch/data
      - ./services/docker-elasticsearch/config/elasticsearch.yml:/bitnami/elasticsearch/conf/elasticsearch_custom.yml
    ports:
      - 9200:9200
    networks:
      - es-net
  # Uncomment for elasticsearch
  redis:
    image: redis
    restart: always
    networks:
      - es-net
    ports:
      - 6379:6379
  # Uncomment for elasticsearch
  elasticdocapi:
    # build: ./services/proudcity-elastic-docs-api
    image: gcr.io/proudcity-1184/proud-elastic-doc-api:kubernetes.6
    restart: always
    ports:
      - 8085:80
    depends_on:
      - redis
    links:
      - 'redis:elasticdocsapiredis.elasticsearch'
      - 'elasticsearch:elasticsearchdocs.elasticsearch'
    networks:
      - es-net
    environment:
      PORT: 80
      ELASTIC: 'elasticsearchdocs.elasticsearch'
      REDIS: 'elasticdocsapiredis.elasticsearch'
      REDISPORT: 6379

# Uncomment for elasticsearch
networks:
  default:
    driver: bridge
  es-net:
    driver: bridge

volumes:
  data01:
    driver: local
#volumes:
#  wp-proudcity-sync:
#    external: true
