version: '2'

services:
  wordpress:
    container_name: wpproudcity_wordpress_1
    depends_on:
      - db
    image: gcr.io/proudcity-1184/wp-proudcity:master-73e8c4ea20c9c7e52325d8ad659f209932fc155e
    volumes:
      #- wp-proudcity-sync:/app/wordpress:nocopy # nocopy is important
      - ./wordpress:/app/wordpress
      # Exclude node_modules dirs for better performance
      - ./node_modules:/app/wordpress/wp-content/plugins/wp-proud-admin/node_modules
      - ./node_modules:/app/wordpress/wp-content/themes/wp-proud-theme/node_modules
      - ./node_modules:/app/wordpress/wp-content/themes/wp-proud-theme-intranet/node_modules
    tty: true
    ports:
      - "8000:80"
    environment:
      AUTH_REQUIRED:
      AUTH_USERNAME:
      AUTH_PASSWORD:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: db
      #WORDPRESS_DB_PORT: "**LinkMe**"
      HOST: localhost:8000
      APP: beta
      WORDPRESS_AUTH_KEY:
      WORDPRESS_SECURE_AUTH_KEY:
      WORDPRESS_LOGGED_IN_KEY:
      WORDPRESS_AUTH_SALT:
      WORDPRESS_SECURE_AUTH_SALT:
      WORDPRESS_LOGGED_IN_SALT:
      WORDPRESS_NONCE_SALT:
      GRAVITATE_ENCRYPTION_KEY:
      STATELESS_MEDIA_KEY_FILE_PATH:
      STATELESS_MEDIA_BUCKET:
      STATELESS_MEDIA_DIRECTORY:
      STATELESS_MEDIA_CACHE_BUSTING: "1" # defaults to false
      REDIS_SESSION: "false" # no longer supported
      PHP_MEMORY_LIMIT: 256M
      SMTP_HOST:
      SMTP_PASS:
      SMTP_USER:
      BLOCK_LOGIN:
      WP_REDIS_BACKEND_HOST:
      WP_REDIS_BACKEND_AUTH:
      ELASTICSEARCH_DOCS_HOST:
      ELASTICSEARCH_HOST:
      UPLOAD_MAX_FILESIZE: 25M
      # GOOGLE_GIT_TOKEN: # set this to download private repos and $WORDPRESS_PLUGINS in entrypoint.sh
      # WORDPRESSORG_PLUGINS:  # These plugins (csv of slugs) will be downloaded on container start (requires $GOOGLE_GIT_TOKEN)
      # WORDPRESS_PLUGINS:  # These plugins (git repo) will be downloaded on container start (requires $GOOGLE_GIT_TOKEN)
      # WORDPRESS_THEMES:  # These themes (git repo) will be downloaded on container start (requires $GOOGLE_GIT_TOKEN)
            #WORDPRESS_PLUGINS: "https://source.developers.google.com/p/proudcity-1184/r/wp-proud-sr-ca-widgets,https://github.com/SenecaSystems/romulus-wordpress-form.git,https://github.com/proudcity/wp-proud-directory.git"
            #WORDPRESSORG_PLUGINS: "buddypress,bp-default-data,buddypress-edit-activity,bbpress,buddydrive"
            #WORDPRESS_THEMES: "https://source.developers.google.com/p/proudcity-1184/r/wp-proud-sr-ca-theme"
      WP_CACHE: 0
      WP_DEBUG: 0
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
#volumes:
#  wp-proudcity-sync:
#    external: true